[package]
name = "prova_pass"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.9.2"

[[target.starknet-contract]]
sierra = true
casm = true

[dev-dependencies]
cairo_test = "2.9.2"
